### PR TITLE
Renamed Person to Restaurant

### PR DESCRIPTION
**Pull request by evanmok2401**
Late Night Renaming Session @yewwoei @chelchia @Meena567

### CODE REVIEW

**Comment by chelchia** [comment]
stunning commits
one of the best in the field of computing

**Comment by yewwoei** [comment]
Much wow.
Future Alan Turing right here.

**Comment by chelchia** [comment]
merging.
style to be fixed later

**Comment by Meena567** [comment]
Teach me your mythical ways senpai.

**Pull request merged**
